services:
  nginx:
     image: nginx:stable-alpine
     ports:
      - 80:80
      - 443:443
     volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wp
      - MYSQL_DATABASE=wp
      - MYSQL_USER=secret
      - MYSQL_PASSWORD=secret

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html